name: sample
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  freezed: ^2.5.7
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  meta: ^1.15.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hive: ^2.2.3
  flutter_secure_storage: ^4.2.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true