name: depolyment
on:
  workflow_dispatch:
    inputs:
      platform:
        description: "select the platform to deploy"
        default: "web"
        type: choice
        options:
          - iOS
          - android
          - web
          - everything
      environment:
        description: "select the environment - prod, stage and dev"
        default: "stage"
        type: choice
        options:
          - production
          - staging
          - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing with ubuntu-latest" 