name: "manual build release"
on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: "select a platform to deploy"
        default: web
        options:
          - iOS
          - android
          - web
          - all
      environment:
        type: choice
        description: "select a environment - prod, stage and dev"
        default: "stage"
        options:
          - production
          - staging
          - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing with ubuntu-latest" 